//! The T0 baseline manifest contract — the schema both engines consume.
//!
//! `scripts/generate_terrain_tiles.py` EMITS `geobase-baseline.json` (shipped
//! beside the tiles, plus a copy at `tests/fixtures/` for this crate's tests);
//! this module OWNS the schema and its validation. The Light Engine mirrors
//! this validation in TypeScript and refuses to enable terrain on a manifest
//! that fails it; the Desktop Engine (Phase 1.0) reuses this type directly.

use geobase_tsdf::Tier;
use serde::{Deserialize, Serialize};

use crate::crs::{validate_lonlat_bounds, CrsError};
use crate::{Crs, CrsPipeline};

/// Errors from parsing or validating a baseline manifest.
#[derive(Debug, thiserror::Error)]
pub enum BaselineError {
    #[error("manifest is not valid JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error("tier '{0}' is not a TSDF tier code")]
    BadTier(String),
    #[error(transparent)]
    Crs(#[from] CrsError),
    #[error("manifest is invalid: {0}")]
    Invalid(String),
}

/// TileJSON-compatible manifest for a tiled T0 baseline, with GeoBase fields.
///
/// The `tiles` templates are relative to the manifest's own directory and
/// consumers must absolutize them — MapLibre will not (maplibre-gl-js #182).
/// This is a strict allowlist: no filesystem paths or hashes belong here
/// (provenance lives in the baseline GPKG's gpkg_metadata, which never ships).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BaselineManifest {
    pub tilejson: String,
    pub name: String,
    pub attribution: String,
    pub classification: String,
    pub tier: String,
    pub tsdf_version: String,
    pub encoding: String,
    pub scheme: String,
    /// Native CRS first, viewer CRS last: the pipeline's store-native →
    /// reproject-for-viewer chain, recorded.
    pub crs_chain: Vec<String>,
    pub elevation_range_m: [f64; 2],
    pub minzoom: u8,
    pub maxzoom: u8,
    /// `[west, south, east, north]` in degrees (EPSG:4326).
    pub bounds: [f64; 4],
    pub tiles: Vec<String>,
}

impl BaselineManifest {
    /// Parse and validate. Every rule here is one both engines rely on to
    /// refuse rendering data that is mis-declared.
    pub fn parse(json: &str) -> Result<Self, BaselineError> {
        let manifest: BaselineManifest = serde_json::from_str(json)?;
        manifest.validate()?;
        Ok(manifest)
    }

    /// The manifest's TSDF tier. Baselines bundled for public deployment
    /// must be T0 — enforced by the tile pipeline at generation time and
    /// re-checked by every consumer.
    pub fn tier(&self) -> Result<Tier, BaselineError> {
        Tier::from_code(&self.tier).ok_or_else(|| BaselineError::BadTier(self.tier.clone()))
    }

    fn validate(&self) -> Result<(), BaselineError> {
        self.tier()?;
        if self.encoding != "terrarium" {
            return Err(BaselineError::Invalid(format!(
                "encoding '{}' is not 'terrarium'",
                self.encoding
            )));
        }
        if self.scheme != "xyz" {
            // MapLibre raster-dem has no `scheme` property; it always requests
            // XYZ. A TMS manifest here means every tile request will 404.
            return Err(BaselineError::Invalid(format!(
                "scheme '{}' is not 'xyz'",
                self.scheme
            )));
        }
        if self.minzoom > self.maxzoom {
            return Err(BaselineError::Invalid(format!(
                "minzoom {} > maxzoom {}",
                self.minzoom, self.maxzoom
            )));
        }
        if self.elevation_range_m[0] > self.elevation_range_m[1] {
            return Err(BaselineError::Invalid("elevation range inverted".into()));
        }
        validate_lonlat_bounds(self.bounds)?;
        for crs in &self.crs_chain {
            Crs(crs.clone()).validate()?;
        }
        match self.crs_chain.last() {
            Some(last) if last == CrsPipeline::VIEWER_CRS => {}
            _ => {
                return Err(BaselineError::Invalid(format!(
                    "crs_chain must end at the viewer CRS {}",
                    CrsPipeline::VIEWER_CRS
                )))
            }
        }
        let template_ok = self
            .tiles
            .first()
            .is_some_and(|t| t.contains("{z}") && t.contains("{x}") && t.contains("{y}"));
        if !template_ok {
            return Err(BaselineError::Invalid(
                "tiles[0] must contain {z}/{x}/{y} placeholders".into(),
            ));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The REAL shipped manifest, regenerated by scripts/generate_terrain_tiles.py
    /// into this crate's fixtures alongside the web copy (single writer, two paths).
    const FIXTURE: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/geobase-baseline.json"
    ));

    #[test]
    fn shipped_manifest_parses_and_validates() {
        let manifest = BaselineManifest::parse(FIXTURE).expect("shipped manifest is valid");
        assert_eq!(
            manifest.tier().unwrap(),
            Tier::T0,
            "public bundle must be T0"
        );
        assert_eq!(manifest.encoding, "terrarium");
        assert_eq!(manifest.scheme, "xyz");
        assert_eq!(manifest.crs_chain.last().unwrap(), CrsPipeline::VIEWER_CRS);
        assert!(manifest.tsdf_version.starts_with("0.9"));
    }

    #[test]
    fn tms_scheme_is_rejected() {
        let tampered = FIXTURE.replace("\"xyz\"", "\"tms\"");
        assert!(BaselineManifest::parse(&tampered).is_err());
    }

    #[test]
    fn unknown_tier_is_rejected() {
        let tampered = FIXTURE.replace("\"tier\": \"T0\"", "\"tier\": \"T9\"");
        assert!(BaselineManifest::parse(&tampered).is_err());
    }

    #[test]
    fn undeclared_fields_are_rejected() {
        // The manifest is an allowlist; a field smuggled in (e.g. a local path)
        // must fail parsing, not pass silently.
        let tampered = FIXTURE.replacen('{', "{\"source_path\": \"D:/secret\",", 1);
        assert!(BaselineManifest::parse(&tampered).is_err());
    }
}
