#!/usr/bin/env python3
"""License audit for GeoBase (C3 release hardening).

Inventories the transitive cargo dependency graph (and, when available, the
pnpm graph) and:

  --check   exits non-zero if any dependency carries a DISALLOWED license
            (strong copyleft — GPL/AGPL — with no permissive alternative in its
            SPDX expression). Weak file-level copyleft (MPL-2.0, LGPL with a
            permissive OR-branch) is allowed and reported.
  --write P writes a generated Markdown inventory to path P.

Dependency-free (stdlib + `cargo`/`pnpm` subprocesses) so it runs in CI without
a bespoke tool. Product code is Apache-2.0; the goal is to keep the distributed
binary free of license terms incompatible with that.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter

# Strong copyleft: disallowed for a distributed Apache-2.0 binary UNLESS the
# SPDX expression offers a permissive alternative (e.g. "GPL-2.0 OR MIT").
STRONG_COPYLEFT = ("GPL-2.0", "GPL-3.0", "AGPL-3.0", "AGPL", "GPL-2.0-only", "GPL-3.0-only")
PERMISSIVE_MARKERS = ("MIT", "APACHE-2.0", "BSD", "UNLICENSE", "ZLIB", "ISC")


def cargo_packages() -> list[dict]:
    # encoding="utf-8": cargo metadata emits UTF-8, but text=True would decode
    # with the Windows default (cp1252) and choke on non-Latin-1 bytes.
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],
        capture_output=True, text=True, encoding="utf-8", check=True,
    )
    return json.loads(out.stdout)["packages"]


def spdx_is_disallowed(expr: str) -> bool:
    """True if the SPDX expression is strong copyleft with no permissive branch."""
    upper = expr.upper()
    if not any(marker in upper for marker in STRONG_COPYLEFT):
        return False
    # Strong copyleft present — allowed only if a permissive alternative exists.
    if " OR " in upper and any(p in upper for p in PERMISSIVE_MARKERS):
        return False
    return True


def audit_cargo() -> tuple[list[tuple[str, str, str]], list[tuple[str, str, str]]]:
    """Return (all_entries, disallowed_entries) as (name, version, license)."""
    entries: list[tuple[str, str, str]] = []
    disallowed: list[tuple[str, str, str]] = []
    for pkg in cargo_packages():
        lic = pkg.get("license") or ("<file: " + str(pkg.get("license_file")) + ">"
                                     if pkg.get("license_file") else "<NONE>")
        entry = (pkg["name"], pkg["version"], lic)
        entries.append(entry)
        if lic == "<NONE>" or (pkg.get("license") and spdx_is_disallowed(pkg["license"])):
            disallowed.append(entry)
    entries.sort()
    return entries, disallowed


def pnpm_licenses() -> dict | None:
    """Best-effort pnpm license listing. Any failure (pnpm absent, no install,
    unexpected output shape) returns None — the cargo audit is the gate; pnpm
    is informational."""
    try:
        out = subprocess.run(
            ["pnpm", "licenses", "list", "--json", "-r"],
            capture_output=True, text=True, encoding="utf-8",
        )
        if out.returncode != 0 or not (out.stdout or "").strip():
            return None
        parsed = json.loads(out.stdout)
        return parsed if isinstance(parsed, dict) else None
    except Exception:
        return None


def render_markdown(entries, disallowed, pnpm) -> str:
    lines = [
        "# Dependency License Inventory (generated)",
        "",
        "Generated by `scripts/license_audit.py`. Do not hand-edit — re-run the",
        "script. Attribution and adapted-code notices live in",
        "`THIRD_PARTY_NOTICES.md`; this file is the exhaustive machine inventory.",
        "",
        "## Cargo (transitive)",
        "",
        f"- Total packages: **{len(entries)}**",
        f"- Disallowed (strong copyleft, no permissive branch): **{len(disallowed)}**",
        "",
        "### License distribution",
        "",
    ]
    dist = Counter(lic for _, _, lic in entries)
    for lic, n in dist.most_common():
        lines.append(f"- {n} × `{lic}`")
    lines += ["", "### All packages", "", "| Package | Version | License |", "|---|---|---|"]
    for name, version, lic in entries:
        lines.append(f"| {name} | {version} | {lic} |")
    if pnpm is not None:
        lines += ["", "## pnpm (transitive)", ""]
        for lic, pkgs in sorted(pnpm.items()):
            names = ", ".join(sorted({p.get("name", "?") for p in pkgs}))
            lines.append(f"- `{lic}`: {names}")
    else:
        lines += ["", "## pnpm", "",
                  "_pnpm license listing not captured in this run "
                  "(run `pnpm install` first, or pnpm unavailable)._"]
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 on a disallowed license")
    parser.add_argument("--write", help="write the Markdown inventory to this path")
    args = parser.parse_args(argv)

    entries, disallowed = audit_cargo()
    pnpm = pnpm_licenses()

    if args.write:
        with open(args.write, "w", encoding="utf-8") as out:
            out.write(render_markdown(entries, disallowed, pnpm))
        print(f"wrote {args.write} ({len(entries)} cargo packages)")

    print(f"cargo: {len(entries)} packages, {len(disallowed)} disallowed")
    if disallowed:
        print("DISALLOWED licenses (strong copyleft, no permissive alternative):", file=sys.stderr)
        for name, version, lic in disallowed:
            print(f"  {name} {version}: {lic}", file=sys.stderr)

    if args.check and disallowed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
